/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Goal = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'targetDate' : IDL.Text,
  'createdTimestamp' : Time,
});
export const HabitView = IDL.Record({
  'id' : IDL.Nat,
  'completionLogs' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdTimestamp' : Time,
});
export const UserProfile = IDL.Record({
  'dateOfBirth' : IDL.Text,
  'themePreference' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGoal' : IDL.Func([IDL.Text, IDL.Text], [Goal], []),
  'createHabit' : IDL.Func([IDL.Text], [HabitView], []),
  'deleteGoal' : IDL.Func([IDL.Nat], [], []),
  'deleteHabit' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getHabitCompletionLog' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
  'getHabits' : IDL.Func([], [IDL.Vec(HabitView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markHabitComplete' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateGoal' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateHabit' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Goal = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'targetDate' : IDL.Text,
    'createdTimestamp' : Time,
  });
  const HabitView = IDL.Record({
    'id' : IDL.Nat,
    'completionLogs' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdTimestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'dateOfBirth' : IDL.Text,
    'themePreference' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGoal' : IDL.Func([IDL.Text, IDL.Text], [Goal], []),
    'createHabit' : IDL.Func([IDL.Text], [HabitView], []),
    'deleteGoal' : IDL.Func([IDL.Nat], [], []),
    'deleteHabit' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getHabitCompletionLog' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getHabits' : IDL.Func([], [IDL.Vec(HabitView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markHabitComplete' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateGoal' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateHabit' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };