/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Goal {
  'id' : bigint,
  'name' : string,
  'targetDate' : string,
  'createdTimestamp' : Time,
}
export interface HabitView {
  'id' : bigint,
  'completionLogs' : Array<string>,
  'name' : string,
  'createdTimestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'dateOfBirth' : string,
  'themePreference' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGoal' : ActorMethod<[string, string], Goal>,
  'createHabit' : ActorMethod<[string], HabitView>,
  'deleteGoal' : ActorMethod<[bigint], undefined>,
  'deleteHabit' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGoals' : ActorMethod<[], Array<Goal>>,
  'getHabitCompletionLog' : ActorMethod<[bigint], Array<string>>,
  'getHabits' : ActorMethod<[], Array<HabitView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markHabitComplete' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateGoal' : ActorMethod<[bigint, string, string], undefined>,
  'updateHabit' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];